#!/bin/bash

echo "========================================"
echo "无Apple开发者账号的iOS应用开发指南"
echo "========================================"
echo ""

echo "========================================"
echo "1. 无开发者账号的开发选项"
echo "========================================"
echo ""
echo "好消息是，即使没有付费的Apple开发者账号，您仍然可以："
echo "- 在Xcode中创建和构建iOS应用"
echo "- 在模拟器上测试应用"
echo "- 在您自己的iOS设备上测试应用（有限制）"
echo "- 使用Capacitor进行开发和调试"
echo ""
echo "主要限制："
echo "- 只能在最多3台个人设备上安装测试应用"
echo "- 应用签名证书有效期仅为7天"
echo "- 无法将应用发布到App Store"
echo "- 某些高级功能和框架可能无法使用"
echo ""
echo "========================================"
echo "2. 使用个人免费账号设置开发环境"
echo "========================================"
echo ""
echo "2.1 在Mac上设置"
echo "----------------------------------------"
echo "1. 确保您已安装最新版本的Xcode"
echo "   - 从Mac App Store下载或更新Xcode"
echo ""
echo "2. 打开Xcode"
echo "   - 导航到 Xcode > Preferences > Accounts"
echo "   - 点击左下角的 '+' 按钮"
echo "   - 选择 'Apple ID' 并点击 'Continue'"
echo "   - 使用您的普通Apple ID（无需开发者账号）登录"
echo ""
echo "2.2 配置项目签名"
echo "----------------------------------------"
echo "1. 在Xcode中打开您的Capacitor iOS项目"
echo "   - 运行: npx cap open ios"
echo ""
echo "2. 在项目导航器中选择您的项目"
echo "   - 选择TARGETS > App"
echo "   - 点击 'Signing & Capabilities' 选项卡"
echo ""
echo "3. 配置签名设置"
echo "   - 勾选 'Automatically manage signing'"
echo "   - 从 'Team' 下拉菜单中选择您登录的Apple ID"
echo "   - Xcode会自动创建必要的证书和配置文件"
echo ""
echo "4. 确认Bundle Identifier"
echo "   - 确保Bundle Identifier格式正确（例如：com.yourname.appname）"
echo "   - 避免使用可能与其他应用冲突的标识符"
echo ""
echo "========================================"
echo "3. 在您的iOS设备上运行应用"
echo "========================================"
echo ""
echo "3.1 准备您的设备"
echo "----------------------------------------"
echo "1. 确保您的iOS设备已更新到最新版本"
echo "2. 将您的iOS设备通过USB连接到Mac"
echo "3. 在设备上，进入 设置 > 通用 > 设备管理（或描述文件与设备管理）"
echo ""
echo "3.2 信任开发者证书"
echo "----------------------------------------"
echo "1. 在Xcode中，选择您连接的设备作为运行目标"
echo "2. 点击运行按钮或按 Command + R"
echo "3. 首次运行时，Xcode可能会提示需要在设备上信任证书"
echo "4. 在您的iOS设备上："
echo "   - 进入 设置 > 通用 > 设备管理"
echo "   - 找到并选择您的Apple ID"
echo "   - 点击 '信任 [您的Apple ID]'"
echo "   - 再次点击 '信任' 确认"
echo ""
echo "3.3 运行应用"
echo "----------------------------------------"
echo "1. 回到Xcode，再次点击运行按钮"
echo "2. 应用应该会在您的设备上安装并启动"
echo "3. 您可以在设备上测试和调试应用"
echo ""
echo "========================================"
echo "4. 证书有效期管理"
echo "========================================"
echo ""
echo "- 使用免费Apple ID创建的开发证书有效期为7天"
echo "- 证书过期后，您需要重新在Xcode中构建并安装应用"
echo "- Xcode会自动重新生成证书"
echo "- 过期后，之前安装的应用将无法打开"
echo ""
echo "如何查看证书有效期："
echo "1. 在Xcode中，进入 Preferences > Accounts"
echo "2. 选择您的Apple ID"
echo "3. 点击 'Manage Certificates...'"
echo "4. 查看证书的有效期信息"
echo ""
echo "========================================"
echo "5. 使用模拟器进行开发"
echo "========================================"
echo ""
echo "如果不想处理证书和设备限制，您可以使用iOS模拟器："
echo ""
echo "1. 在Xcode中，选择任何iOS模拟器作为运行目标"
echo "2. 点击运行按钮，应用会在模拟器中启动"
echo "3. 模拟器没有证书限制，可以无限期使用"
echo "4. 注意：某些特定于设备的功能（如相机、推送通知）在模拟器中可能无法完全测试"
echo ""
echo "========================================"
echo "6. 替代方案和注意事项"
echo "========================================"
echo ""
echo "6.1 TestFlight Beta测试（仍需开发者账号）"
echo "----------------------------------------"
echo "- 如果有朋友或同事拥有开发者账号，他们可以将您添加为内部测试人员"
echo "- 这样您可以通过TestFlight安装和测试应用"
echo "- 内部测试没有设备数量限制"
echo ""
echo "6.2 企业证书（需要企业开发者账号）"
echo "----------------------------------------"
echo "- 企业开发者账号可以创建不经过App Store分发的应用"
echo "- 适合企业内部应用分发"
echo "- 费用较高（每年299美元）"
echo ""
echo "6.3 开源替代方案"
echo "----------------------------------------"
echo "- 考虑使用Web App + PWA（Progressive Web App）"
echo "- 可以在没有开发者账号的情况下，提供接近原生的体验"
echo "- 用户可以将Web App添加到主屏幕"
echo ""
echo "========================================"
echo "7. Capacitor开发提示"
echo "========================================"
echo ""
echo "7.1 热重载开发"
echo "----------------------------------------"
echo "- 在开发过程中使用热重载可以加快开发速度："
echo "  npm run dev"
echo "  npx cap copy"
echo "  npx cap run ios --livereload"
echo ""
echo "7.2 调试技巧"
echo "----------------------------------------"
echo "- 使用Safari开发工具调试设备上的应用："
echo "  1. 在Mac上的Safari中，启用 开发 > 显示开发菜单"
echo "  2. 连接iOS设备后，可以通过 开发 > [设备名称] > [应用名称] 访问Web Inspector"
echo ""
echo "========================================"
echo "总结"
echo "========================================"
echo ""
echo "虽然没有Apple开发者账号，您仍然可以："
echo "1. 在模拟器上自由开发和测试"
echo "2. 在最多3台个人设备上进行有限的测试（7天证书有效期）"
echo "3. 使用Capacitor进行跨平台开发"
echo ""
echo "但是，如果您计划："
echo "- 发布应用到App Store"
echo "- 在无限设备上测试应用"
echo "- 使用所有iOS功能"
echo "- 分发应用给更多用户"
echo "那么您需要注册Apple开发者账号（每年99美元）"
echo ""
echo "========================================