#!/bin/bash

echo "========================================"
echo "Xcode中配置'Automatically manage signing'详细指南"
echo "========================================"
echo ""
echo "此指南将详细说明如何在Xcode中找到并配置自动签名管理选项"
echo "适用于使用普通Apple ID进行iOS应用开发测试"
echo ""
echo "========================================"
echo "第1步：打开您的Capacitor iOS项目"
echo "========================================"
echo ""
echo "1. 打开终端"
echo "2. 导航到您的项目目录"
echo "   cd /Users/dickphilipp/Documents/revelation"
echo "3. 运行命令打开iOS项目"
echo "   npx cap open ios"
echo ""
echo "这将自动启动Xcode并打开您的Capacitor iOS项目"
echo ""
echo "========================================"
echo "第2步：在Xcode中找到项目设置"
echo "========================================"
echo ""
echo "1. 在Xcode的左侧项目导航器中，点击顶部的项目文件"
echo "   （通常显示为蓝色的项目图标，名称为'App'）"
echo ""
echo "   视觉指南："
echo "   ┌─────────────────────────────────┐"
echo "   │ Project Navigator ▼             │"
echo "   ├─────────────────────────────────┤"
echo "   │ ▼ App                           │ <-- 点击这里"
echo "   │   ▼ App                         │"
echo "   │   ▼ App.xcodeproj               │"
echo "   │   ▼ Pods                        │"
echo "   └─────────────────────────────────┘"
echo ""
echo "2. 点击后，右侧将显示项目配置界面"
echo ""
echo "========================================"
echo "第3步：配置签名设置"
echo "========================================"
echo ""
echo "1. 在右侧配置界面中，确保选中'TARGETS'下的'App'"
echo ""
echo "   视觉指南："
echo "   ┌─────────────────────────────────┐"
echo "   │ PROJECT  TARGETS ▼              │"
echo "   │ ┌────────┐ ┌────────┐           │"
echo "   │ │ App    │ │ App    │ <-- 选中   │"
echo "   │ └────────┘ └────────┘           │"
echo "   └─────────────────────────────────┘"
echo ""
echo "2. 点击顶部的'Signing & Capabilities'选项卡"
echo ""
echo "   视觉指南："
echo "   ┌─────────────────────────────────┐"
echo "   │ General Info Build Phases       │"
echo "   │ ▼ Signing & Capabilities        │ <-- 点击这里"
echo "   │ Resource Tags                   │"
echo "   └─────────────────────────────────┘"
echo ""
echo "3. 找到'Automatically manage signing'选项"
echo "   - 勾选这个复选框"
echo "   - 确保复选框内有一个勾号（✓）"
echo ""
echo "   视觉指南："
echo "   ┌─────────────────────────────────┐"
echo "   │ Signing                         │"
echo "   │ □ Automatically manage signing  │ <-- 勾选为 ■"
echo "   │ Team: ▼                         │"
echo "   │ Bundle Identifier: com.revelationreader.app │"
echo "   └─────────────────────────────────┘"
echo ""
echo "4. 在'Team'下拉菜单中选择您的Apple ID"
echo "   - 如果您还没有登录，Xcode会提示您登录"
echo "   - 使用您的普通Apple ID（无需开发者账号）登录"
echo ""
echo "========================================"
echo "第4步：验证Bundle Identifier设置"
echo "========================================"
echo ""
echo "1. 确保Bundle Identifier格式正确"
echo "   - 格式通常为：com.companyname.appname"
echo "   - 您的项目当前设置为：com.revelationreader.app"
echo ""
echo "2. 如果需要修改，直接在输入框中编辑"
echo "   - 确保使用唯一的标识符以避免冲突"
echo ""
echo "========================================"
echo "第5步：等待Xcode处理签名设置"
echo "========================================"
echo ""
echo "1. 勾选'Automatically manage signing'后，Xcode会自动："
echo "   - 检查您的开发者账号状态"
echo "   - 为您创建必要的开发证书"
echo "   - 生成开发配置文件"
echo "   - 配置项目的签名设置"
echo ""
echo "2. 观察Xcode顶部状态栏"
echo "   - 等待签名处理完成"
echo "   - 确保没有出现错误提示"
echo ""
echo "========================================"
echo "常见问题与解决方案"
echo "========================================"
echo ""
echo "1. 如果Xcode提示无法登录Apple ID："
echo "   - 确保您的Apple ID有效且未被锁定"
echo "   - 检查网络连接"
echo "   - 尝试在系统偏好设置中先登录Apple ID"
echo ""
echo "2. 如果遇到'No profiles for 'com.yourname.app' were found'错误："
echo "   - 确保Bundle Identifier格式正确"
echo "   - 尝试点击'Fix Issue'按钮（如果出现）"
echo "   - 重新登录您的Apple ID"
echo ""
echo "3. 如果遇到证书相关错误："
echo "   - 在Xcode > Preferences > Accounts中检查证书状态"
echo "   - 尝试点击'Download Manual Profiles'按钮"
echo "   - 必要时删除过期证书并让Xcode重新生成"
echo ""
echo "========================================"
echo "验证配置是否成功"
echo "========================================"
echo ""
echo "成功配置后，您应该能看到："
echo "1. 'Automatically manage signing'复选框被勾选"
echo "2. Team下拉菜单显示您的Apple ID"
echo "3. 没有红色或黄色警告图标"
echo "4. 可以选择连接的iOS设备作为运行目标"
echo ""
echo "现在您可以尝试在模拟器或连接的iOS设备上运行应用了！"
echo ""
echo "========================================